import type { ImageSourcePropType } from 'react-native';

import { BRAND_NAME } from '@forms/shared/brand';
import type { Measurements, OrderStatus } from '@forms/shared';

import guardKeeper from '../../assets/products/guard-keeper.jpg';
import guardPair from '../../assets/products/guard-pair.jpg';
import guardSingle from '../../assets/products/guard-single.jpg';

import { SLICE_DIMS, SLICES, sliceKey, type MeasurementRow, type Scan } from './library';
import { getSupabaseClient, hasSupabaseConfig } from './supabase';

export type { Scan } from './library';

/**
 * Data-layer stubs for the product surface (scans, orders, products). Phase
 * 0/1: no backend schema is final yet, so every function is safe to call with
 * zero configuration - with no Supabase env vars it returns the demo rows
 * below rather than throwing. Once
 * Supabase tables exist (docs/DESIGN.md section 8), the real query replaces
 * the stub inside each function; call sites (hooks in src/hooks/) do not
 * change.
 */

const USE_FAKE_DATA = !hasSupabaseConfig();

/** Library page size. The tab shows recent history, not an archive; raise or
 * paginate when someone actually has this many scans. */
export const SCAN_LIST_LIMIT = 100;

export interface Order {
  id: string;
  productName: string;
  status: OrderStatus;
  /** Null until checkout sets the charged amount. */
  totalCents: number | null;
  currency: string;
  /** Set by the admin panel when the order ships. */
  trackingCarrier: string | null;
  trackingNumber: string | null;
  createdAt: string;
}

export interface Product {
  id: string;
  name: string;
  description: string;
  priceCents: number;
  // Absent for real rows until the products table carries imagery; screens
  // must render without it. Typed as a source, not a URL, so a bundled asset
  // and a future remote { uri } row both fit the one field.
  image?: ImageSourcePropType;
}

/**
 * Demo rows for USE_FAKE_DATA mode, so every list screen renders populated in
 * a zero-backend dev build. Prices and the guard name mirror
 * supabase/seed.sql; ids are fixed strings, not uuids, because nothing here
 * is ever written back. Real rows replace these the moment
 * EXPO_PUBLIC_SUPABASE_* are set.
 */
// Renders of the guard, generated by assets/products/render-guards.py (the
// contour lines are the S1-S4 slice planes). Placeholders for real product
// photography, which replaces them without touching this shape.
const DEMO_PRODUCTS: Product[] = [
  {
    id: 'demo-custom-guard',
    name: `${BRAND_NAME} Custom Shin Guard`,
    description: 'Printed to your scan. One piece, vented shell, no strap gap at the ankle.',
    priceCents: 8900,
    image: guardSingle,
  },
  {
    id: 'demo-custom-guard-pair',
    name: `${BRAND_NAME} Custom Shin Guard (pair)`,
    description: 'Both legs scanned separately, so the left is not a mirror of the right.',
    priceCents: 16900,
    image: guardPair,
  },
  {
    id: 'demo-keeper-guard',
    name: `${BRAND_NAME} Keeper Guard`,
    description: 'Taller shell and a softer liner for goalkeepers taking shots at close range.',
    priceCents: 10900,
    image: guardKeeper,
  },
];

// Sessions covering every state the Library renders: a finished pair, a pair
// still measuring, a pair where one leg failed, and an unpaired single leg.
const DEMO_SCANS: Scan[] = [
  demoScan('demo-scan-1', 'demo-pair-1', 'L', 'ready', '2026-08-28T17:04:00.000Z'),
  demoScan('demo-scan-2', 'demo-pair-1', 'R', 'ready', '2026-08-28T17:12:00.000Z'),
  demoScan('demo-scan-3', 'demo-pair-2', 'L', 'ready', '2026-09-27T10:20:00.000Z'),
  demoScan('demo-scan-4', 'demo-pair-2', 'R', 'processing', '2026-09-27T10:29:00.000Z'),
  demoScan('demo-scan-5', 'demo-pair-3', 'L', 'failed', '2026-08-21T09:41:00.000Z'),
  demoScan('demo-scan-6', 'demo-pair-3', 'R', 'ready', '2026-08-21T09:50:00.000Z'),
  demoScan('demo-scan-7', null, 'R', 'ready', '2026-07-30T16:15:00.000Z'),
];

function demoScan(
  id: string,
  pairId: string | null,
  leg: Scan['leg'],
  status: Scan['status'],
  createdAt: string,
): Scan {
  return { id, pairId, leg, status, createdAt };
}

/** Plausible values inside the schema's ranges (validated in api.test.ts):
 * the leg narrows toward the ankle, so S1 is the smallest slice. */
function demoMeasurements(legLength: number, ankleWidth: number): Measurements {
  const values = { Leg_Length: legLength } as Measurements;
  SLICES.forEach((slice, i) => {
    const width = ankleWidth + i * 14;
    SLICE_DIMS.forEach((dim, j) => {
      values[sliceKey(slice, dim)] = Math.round((width + j * 3) * 10) / 10;
    });
  });
  return values;
}

const DEMO_MEASUREMENTS: MeasurementRow[] = [
  {
    scanId: 'demo-scan-1',
    values: demoMeasurements(392, 61),
    createdAt: '2026-08-28T17:30:00.000Z',
  },
  {
    scanId: 'demo-scan-2',
    values: demoMeasurements(394, 63),
    createdAt: '2026-08-28T17:38:00.000Z',
  },
  {
    scanId: 'demo-scan-3',
    values: demoMeasurements(401, 62),
    createdAt: '2026-09-27T10:45:00.000Z',
  },
  {
    scanId: 'demo-scan-6',
    values: demoMeasurements(389, 60),
    createdAt: '2026-08-21T10:05:00.000Z',
  },
  {
    scanId: 'demo-scan-7',
    values: demoMeasurements(386, 59),
    createdAt: '2026-07-30T16:30:00.000Z',
  },
];

const DEMO_ORDERS: Order[] = [
  {
    id: 'demo-order-1',
    productName: `${BRAND_NAME} Custom Shin Guard (pair)`,
    status: 'in_production',
    totalCents: 16900,
    currency: 'usd',
    trackingCarrier: null,
    trackingNumber: null,
    createdAt: '2026-08-29T10:02:00.000Z',
  },
  {
    id: 'demo-order-2',
    productName: `${BRAND_NAME} Custom Shin Guard`,
    status: 'delivered',
    totalCents: 8900,
    currency: 'usd',
    trackingCarrier: 'UPS',
    trackingNumber: '1Z999AA10123456784',
    createdAt: '2026-07-14T15:37:00.000Z',
  },
];

export async function listScans(): Promise<Scan[]> {
  if (USE_FAKE_DATA) {
    return DEMO_SCANS.filter((scan) => !demoDeleted.has(scan.id));
  }
  const { data, error } = await getSupabaseClient()
    .from('scans')
    .select('id, leg, status, pair_id, created_at')
    .is('deleted_at', null)
    .order('created_at', { ascending: false })
    .limit(SCAN_LIST_LIMIT);
  if (error) {
    throw error;
  }
  return (data ?? []).map((row) => ({
    id: row.id,
    leg: row.leg,
    status: row.status,
    pairId: row.pair_id,
    createdAt: row.created_at,
  }));
}

/** Validated measurement rows for the given scans (both legs of one session).
 * RLS "measurements: select own via scan" scopes this to the user's own scans;
 * unvalidated rows are filtered server-side so they never reach the device. */
export async function listMeasurements(scanIds: readonly string[]): Promise<MeasurementRow[]> {
  if (scanIds.length === 0) {
    return [];
  }
  if (USE_FAKE_DATA) {
    return DEMO_MEASUREMENTS.filter((row) => scanIds.includes(row.scanId));
  }
  const { data, error } = await getSupabaseClient()
    .from('measurements')
    .select('scan_id, values, created_at')
    .in('scan_id', scanIds)
    .eq('validated', true)
    .order('created_at', { ascending: false })
    .limit(20);
  if (error) {
    throw error;
  }
  return (data ?? []).map((row) => ({
    scanId: row.scan_id,
    values: row.values,
    createdAt: row.created_at,
  }));
}

/** Same cap as the library: recent history, not an archive. */
export const ORDER_LIST_LIMIT = 50;

// Row shapes as PostgREST returns them for the selects below; columns match
// supabase/migrations 0001 + 0009. orders has no name or currency of its own,
// both come from the products join.
export interface OrderQueryRow {
  id: string;
  status: OrderStatus;
  amount_cents: number | null;
  tracking_carrier: string | null;
  tracking_number: string | null;
  created_at: string;
  products: { name: string; currency: string } | null;
}

export interface ProductQueryRow {
  id: string;
  name: string;
  description: string;
  base_price_cents: number;
  image_url: string | null;
}

export function toOrder(row: OrderQueryRow): Order {
  return {
    id: row.id,
    productName: row.products?.name ?? 'Shin guard',
    status: row.status,
    totalCents: row.amount_cents,
    currency: row.products?.currency ?? 'usd',
    trackingCarrier: row.tracking_carrier,
    trackingNumber: row.tracking_number,
    createdAt: row.created_at,
  };
}

export function toProduct(row: ProductQueryRow): Product {
  return {
    id: row.id,
    name: row.name,
    description: row.description,
    priceCents: row.base_price_cents,
    ...(row.image_url ? { image: { uri: row.image_url } } : {}),
  };
}

/** Demo-mode deletions, so the delete flow is clickable with no backend.
 * Lives only as long as the JS session, like everything else in fake mode. */
const demoDeleted = new Set<string>();

/**
 * Delete one session (both legs). The RPC (supabase/migrations/0011) checks
 * ownership, refuses scans on an order and hides them at once; the purge
 * worker erases the files afterwards. Throws the PostgREST error as is, so
 * deleteErrorMessage can branch on its SQLSTATE code.
 */
export async function requestScanDeletion(scanIds: readonly string[]): Promise<void> {
  if (USE_FAKE_DATA) {
    scanIds.forEach((id) => demoDeleted.add(id));
    return;
  }
  const { error } = await getSupabaseClient().rpc('request_scan_deletion', {
    p_scan_ids: scanIds,
  });
  if (error) {
    throw error;
  }
}

export async function listOrders(): Promise<Order[]> {
  if (USE_FAKE_DATA) {
    return DEMO_ORDERS;
  }
  const { data, error } = await getSupabaseClient()
    .from('orders')
    .select(
      'id, status, amount_cents, tracking_carrier, tracking_number, created_at, products(name, currency)',
    )
    .order('created_at', { ascending: false })
    .limit(ORDER_LIST_LIMIT);
  if (error) {
    throw error;
  }
  return ((data ?? []) as unknown as OrderQueryRow[]).map(toOrder);
}

/** Only products the admin panel marked available. Cheapest first, so the
 * single guard leads and the pair follows. */
export async function listProducts(): Promise<Product[]> {
  if (USE_FAKE_DATA) {
    return DEMO_PRODUCTS;
  }
  const { data, error } = await getSupabaseClient()
    .from('products')
    .select('id, name, description, base_price_cents, image_url')
    .eq('active', true)
    .order('base_price_cents')
    .limit(50);
  if (error) {
    throw error;
  }
  return ((data ?? []) as ProductQueryRow[]).map(toProduct);
}
